import type { Metadata } from "next";
import React from "react";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import "./globals.css"

export const metadata: Metadata = {
  title: "Ecommerce Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='selection:bg-amber-100 selection:text-amber-950'>
          <Header />
            {children}
          <Footer />
      </body>
    </html>
  );
}
